### ISSUE TITLE
aws s3 cp [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by mariotacke** [aws/aws-cli#2213]
I'm getting an error on Windows trying to `cp` or `sync` from S3: `[Errno 2] No such file or directory`. The files I want to copy or sync download correctly but the process exists with exit 1. Why does it throw an error and why is it trying to sync an empty folder?

### CLI
```sh
aws --version
aws-cli/1.10.67 Python/2.7.9 Windows/8 botocore/1.4.57
```

### Bucket Structure
```
my-bucket
  - test
    - test-file.txt
```

### Command
```
aws s3 cp s3://my-bucket/test . --recursive
> download: s3://my-bucket/test/test-file.txt to .\test-file.txt
> download failed: s3://my-bucket/test/ to .\ [Errno 2] No such file or 
  directory: u'C:\\Users\\my-username\\s3\\'
```

The same exact error occurs when I use `sync`.

Any idea what I am doing wrong? There are no other files in my bucket or sub-folder.

**Comment by mariotacke** [comment]
This issue remains a problem in: 1.11.0 
`aws-cli/1.11.0 Python/2.7.9 Windows/8 botocore/1.4.58`

**Comment by kyleknap** [comment]
@mariotacke So this is the part that looks a little fishy
```
download failed: s3://my-bucket/test/ to .\ [Errno 2] No such file or directory: u'C:\\Users\\my-username\\s3\\'
```
Could you run on a list objects on that key?
```
$ aws s3 ls s3://my-bucket/test/
```
I have a feeling the key is of non-zero size. If it is of non-zero size, the reason you are seeing this is because when a file ends with ``/`` or ``\`` for windows it implies that it is a directory and it is invalid otherwise to have a file with that name and when the CLI tries to download it as a file, it will throw errors. The key needs to be of size zero for the CLI to skip over it.

If this is not the case, could you provide debug logs for the command you are running as I was not able to reproduce it?

**Comment by mariotacke** [comment]
Interesting.

Running with `/` and without produces two different outputs. `cp` and `sync` don't seem to be affected by the `/` or no `/`.

```
aws s3 ls s3://my-bucket/test/
2016-10-04 14:23:59          1              <-------- i guess thats the problem?
2016-10-04 14:23:59          5 testfile.txt
```

```
aws s3 ls s3://my-bucket/test
                           PRE test/
```

Right now I am using S3 Browser to upload files to my bucket. I created an empty folder on Windows, put the `testfile.txt` into it and uploaded it. Is there a better way to do this?

**Comment by mariotacke** [comment]
I ran:

```
aws s3 rm s3://my-bucket/test/
delete: s3://my-bucket/test/
```

Now it works fine. I wonder what I can do on Windows to prevent creating this unnecessary file during a folder upload?

**Comment by kyleknap** [comment]
So are using the AWS Console and Windows to upload the directory with the file in it and can you reproduce this every time? Usually when you click the create directory button in the AWS Console, the console will usually create an empty object ending with ``/``. So I find it strange that it made it of size nonzero. It also seems strange that the behavior of the console differs based on operating system.

**Comment by mariotacke** [comment]
Sorry, that was a misunderstanding: when I use the CLI everything works fine (upload, sync/cp). Previously I used this software [S3 Browser](http://s3browser.com/) which seems to create a non-zero file for any uploaded directory from Windows. On OSX, I use [Cyberduck](https://cyberduck.io) which does not cause a problem. My issue is solved by not using the S3 Browser software. With your help I was able to identify and remedy the issue. You can close the issue. Thanks!

**Comment by kyleknap** [comment]
Sounds good. Glad you were able to figure things out. Closing.

**Comment by snehalpatil10** [comment]
hello,i have same issue in displaying image from s3 bucket to lambda function.can you please help me

**Comment by stephen-ifmacinema** [comment]
This issue still persist for me. It occurs when I try to copy large files say 2GB from s3 to ec2 using a lambda function

It works perfectly for smaller files

ex. aws s3 cp s3://bucket/file.log  log_store/file.log

aws --version
aws-cli/2.1.36 Python/3.8.8 Linux/4.18.0-240.15.1.el8_3.x86_64 exe/x86_64.rhel.8 prompt/off

**Comment by unfor19** [comment]
I had the same issue, and after a lot of debugging, I enabled [Windows long paths](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry), and the issue went away.

Here's how I did it:

> The registry key Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathsEnabled (Type: REG_DWORD) must exist and be set to 1. The key's value will be cached by the system (per process) after the first call to an affected Win32 file or directory function (see below for the list of functions). The registry key will not be reloaded during the lifetime of the process. In order for all apps on the system to recognize the value of the key, a reboot might be required because some processes may have started before the key was set.
