### ISSUE TITLE
Can't install awscli using Python 3.7

### ISSUE THREAD

**Issue by ViktorHaag** [aws/aws-cli#3427]
It seems like awscli pinning to an older version of `pyyaml` is, at least for the moment, causing a problem attempting to install under Python3.7.

See (https://github.com/yaml/pyyaml/issues/126) for reference.

The PyYAML team is apparently attempting to release a fixed package for 3.7 users, but it looks like it might require `4.2b4` at the earliest; it's unclear to me whether they'll provide re-built wheels for older versions like the ones that awscli relies upon.

As the default Python3 with homebrew is now 3.7, I expect this will cause widespread breakages for awcli users.

Is it possible to un-pin the PyYAML dependency and reset it to >4.1?

See also #2290 and #3414

**Comment by ViktorHaag** [comment]
Closed as addressed with #3414

**Comment by JordonPhillips** [comment]
Gonna re-open this until we actually merge a fix. Generally speaking I wouldn't want to upgrade to 4.x even if it appears at first glance to be safe, at least not without a thorough vetting. But it does look like they're going to release 3.13 soon which will be 3.12 exactly but with 3.7 support. Looks like their current plans are to put that out on Thursday: https://github.com/yaml/pyyaml/issues/193

**Comment by JordonPhillips** [comment]
Another complication to this is that we can't set Travis up for testing. The only way to do that right now is to use an undocumented experimental image with elevated privileges, or use a pre-release version that isn't wholly representative of the state of the released version.

**Comment by number5** [comment]
Here is the temporary fix to install awscli or boto3 on Python 3.7 https://gist.github.com/number5/015eef7783e7ddf7d5a4176d4e6bc975

(Should not be required after pyyaml release 3.13 on 5th July)

**Comment by asottile** [comment]
I just opened #3430 which enables the re-release of 3.12: 3.13

**Comment by tylerhackbart** [comment]
Anyone still having this issue, our team is

**Comment by jakul** [comment]
@tylerhackbart You need to wait for https://github.com/aws/aws-cli/pull/3430 to be merged & released.

**Comment by bureson** [comment]
@JordonPhillips the MR is ready and there is even a workaround for Travis, can you prioritize it please?

**Comment by antonioned** [comment]
I have the `pip install awscli` working on circleci, that has been fixed. But the `pip install awsebcli` is not. Anything on this ?

**Comment by ilanbiala** [comment]
When I run the following, AWS configure is still looking for Python 3.6...has this been fixed?
```shell
$ aws configure
-bash: /usr/local/bin/aws: /usr/local/opt/python3/bin/python3.6: bad interpreter: No such file or directory
```

**Comment by justnance** [comment]
It appears all the related PRs are merged and the work is complete.   I am setting this issue to close soon pending any new feedback.

**Comment by bitfede** [comment]
Still experiencing the same issue as the user @ilanbiala 

I get this error when trying to execute the aws cli:

```
-bash: /Users/fede/Library/Python/3.7/bin/aws: /usr/local/opt/python/bin/python3.7: bad interpreter: No such file or directory
```

The suggested solution of running `brew reinstall awscli` does not fix the problem... Anyone has had this similar issue?

**Comment by dwene** [comment]
I also am experiencing this issue. Tried reinstalling `awscli` also, still get the same error as @bitfede.
It appears I'm on python version `3.8.5`, wondering why it hard links to 3.7.

**Comment by matthinea** [comment]
Hack, but installing python@3.7 via homebrew and then `cp`ing that installation into the directory expected by awscli cleared the error for me.

```shell
brew install python@3.7
cp -r /usr/local/opt/python@3.7/bin/python3.7 /usr/local/opt/python/bin/python3.7
```
