### ISSUE TITLE
Unable to install awscli 

### ISSUE THREAD

**Issue by bvandermeersch** [aws/aws-cli#6064]
Since the Friday update my CI/CD pipeline is unable to install aws-cli

```
$ pip install awscli
Collecting awscli
  Downloading https://files.pythonhosted.org/packages/be/d0/00369b4001c5916e33d54055a7a3ed451bcb4c7679f65a80f6ba5b7c01a2/awscli-1.19.44-py2.py3-none-any.whl (3.6MB)
Collecting colorama<0.4.4,>=0.2.5 (from awscli)
  Downloading https://files.pythonhosted.org/packages/c9/dc/45cdef1b4d119eb96316b3117e6d5708a08029992b2fee2c143c7a0a5cc5/colorama-0.4.3-py2.py3-none-any.whl
Collecting PyYAML<5.5,>=3.10 (from awscli)
  Downloading https://files.pythonhosted.org/packages/a0/a4/d63f2d7597e1a4b55aa3b4d6c5b029991d3b824b5bd331af8d4ab1ed687d/PyYAML-5.4.1.tar.gz (175kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
  Complete output from command /usr/bin/python2 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-b6L4p9 --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel Cython:
  Collecting setuptools
    Downloading https://files.pythonhosted.org/packages/94/75/05e1d69c61c4dfaf65ad12785cd18bedc1e0129976c55914d6aea59c7da8/setuptools-54.2.0.tar.gz (2.1MB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
      Complete output from command python setup.py egg_info:
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "pkg_resources/__init__.py", line 1367
          raise SyntaxError(e) from e
                                  ^
      SyntaxError: invalid syntax
      ----------------------------------------
  Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-nnn0wV/setuptools/
  ----------------------------------------
Command "/usr/bin/python2 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-b6L4p9 --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel Cython" failed with error code 1 in None
```

**Comment by cavargas40** [comment]
Having the same issue here. Probably will need to install a specific version to prevent this issue.

**Comment by bvandermeersch** [comment]
> I'm having the same issue here. Probably will need to install a specific version to prevent this issue.

I tried rolling back to an older version without luck.

However, the issue seems to have resolved itself for me.

**Comment by kdaily** [comment]
Looks like you're using Python 2? You're trying to get `setuptools-54.2.0` but can only use `setuptools<45` for Python 2:

https://setuptools.readthedocs.io/en/latest/python%202%20sunset.html

I'm looking to see if any of the CLI or `botocore` dependencies changed that would impact this.

**Comment by 1upD** [comment]
I seem to be having a very similar issue trying to install awscli on a system with Python 2.7 right now.
`Collecting awscli
  Downloading awscli-1.19.45.tar.gz (1.4MB)
    100% |████████████████████████████████| 1.4MB 403kB/s 
    Complete output from command python setup.py egg_info:
    /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    error in awscli setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
`

I think this error is because setuptools is out of date. Trying to install setuptools, I'm running into difficulty installing a version that works with Python 2.7.

**Comment by KostyaRolique** [comment]
I receive such issue trying to install awscli with Python 2.7:
```
Collecting awscli
  Downloading https://files.pythonhosted.org/packages/3f/17/dfc4ec7991f2d98c4c6e6cf31a24066828ba82c739ffc2f9f9b11bfe0dec/awscli-1.19.45.tar.gz (1.4MB)
    100% |████████████████████████████████| 1.4MB 842kB/s eta 0:00:01
Exception:
Traceback (most recent call last):
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pip/commands/install.py", line 299, in run
    requirement_set.prepare_files(finder)
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pip/req/req_set.py", line 647, in _prepare_file
    set(req_to_install.extras) - set(dist.extras)
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2810, in extras
    return [dep for dep in self._dep_map if dep]
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2624, in _dep_map
    dm.setdefault(extra,[]).extend(parse_requirements(reqs))
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2980, in parse_requirements
    "version spec")
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2956, in scan_list
    raise RequirementParseError(msg, line, "at", line[p:])
RequirementParseError: Expected ',' or end-of-list in rsa>=3.1.2,<=4.5.0; python_version=="2.7" at ; python_version=="2.7"
You are using pip version 8.1.1, however version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

This error came since this release `v1.20.41`: https://github.com/aws/aws-cli/commit/557aa77bb7f807c641ad9a881869622eae9abf60

**Comment by kdaily** [comment]
Hi @KostyaRolique, @1upD (and anyone else experiencing this issue) - thanks for the reports.

Can you confirm what your environment looks like?

1. Operating system
2. CLI version you're trying to install, and 
3. Output of `pip list` or the like to look at what's installed.

@KostyaRolique - it looks like you're experiencing a separate issue and need to upgrade `pip`.

@1upD - the link I posted about Python 2 sunsetting for `setuptools` lists some workarounds to get an appropriate version installed.

As a reminder to all, the AWS CLI will drop support for Python 2 on July 15, 2021:

https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-python-2-7-in-aws-sdk-for-python-and-aws-cli-v1/

**Comment by vauchok** [comment]
Hi all,

I think it fixed in awscli-1.19.46:

`
Apr 07 07:41:08 ip-x-x-x-x.ec2.internal user-data[1530]: + pip install awscli
Apr 07 07:41:08 ip-x-x-x-x.ec2.internal user-data[1530]: Collecting awscli
Apr 07 07:41:09 ip-x-x-x-x.ec2.internal user-data[1530]:   Downloading https://files.pythonhosted.org/packages/ce/0c/6287e948fbfa62811ddea534b7fc45c407b34e5d1781a220ea7b01df02fe/awscli-1.19.46-py2.py3-none-any.whl (3.6MB)
Apr 07 07:41:10 ip-x-x-x-x.ec2.internal user-data[1530]: Collecting rsa<=4.5.0,>=3.1.2; python_version == "2.7" (from awscli)
Apr 07 07:41:10 ip-x-x-x-x.ec2.internal user-data[1530]:   Downloading https://files.pythonhosted.org/packages/26/f8/8127fdda0294f044121d20aac7785feb810e159098447967a6103dedfb96/rsa-4.5-py2.py3-none-any.whl
Apr 07 07:41:10 ip-x-x-x-x.ec2.internal user-data[1530]: Collecting colorama<0.4.4,>=0.2.5 (from awscli)
Apr 07 07:41:10 ip-x-x-x-x.ec2.internal user-data[1530]:   Downloading https://files.pythonhosted.org/packages/c9/dc/45cdef1b4d119eb96316b3117e6d5708a08029992b2fee2c143c7a0a5cc5/colorama-0.4.3-py2.py3-none-any.whl
Apr 07 07:41:10 ip-x-x-x-x.ec2.internal user-data[1530]: Requirement already satisfied (use --upgrade to upgrade): PyYAML<5.5,>=3.10 in /usr/lib64/python2.7/site-packages (from awscli)
Apr 07 07:41:10 ip-x-x-x-x.ec2.internal user-data[1530]: Collecting s3transfer<0.4.0,>=0.3.0 (from awscli)
Apr 07 07:41:10 ip-x-x-x-x.ec2.internal user-data[1530]:   Downloading https://files.pythonhosted.org/packages/98/14/0b4be62b65c52d6d1c442f24e02d2a9889a73d3c352002e14c70f84a679f/s3transfer-0.3.6-py2.py3-none-any.whl (73kB)
Apr 07 07:41:10 ip-x-x-x-x.ec2.internal user-data[1530]: Collecting docutils<0.16,>=0.10 (from awscli)
Apr 07 07:41:10 ip-x-x-x-x.ec2.internal user-data[1530]:   Downloading https://files.pythonhosted.org/packages/3a/dc/bf2b15d1fa15a6f7a9e77a61b74ecbbae7258558fcda8ffc9a6638a6b327/docutils-0.15.2-py2-none-any.whl (548kB)
Apr 07 07:41:10 ip-x-x-x-x.ec2.internal user-data[1530]: Collecting botocore==1.20.46 (from awscli)
Apr 07 07:41:11 ip-x-x-x-x.ec2.internal user-data[1530]:   Downloading https://files.pythonhosted.org/packages/6b/3b/3944ed014ba8180e32054f42944988224b3213c3ee423df0e7a156406c7d/botocore-1.20.46-py2.py3-none-any.whl (7.4MB)
Apr 07 07:41:12 ip-x-x-x-x.ec2.internal user-data[1530]: Collecting pyasn1>=0.1.3 (from rsa<=4.5.0,>=3.1.2; python_version == "2.7"->awscli)
Apr 07 07:41:12 ip-x-x-x-x.ec2.internal user-data[1530]:   Downloading https://files.pythonhosted.org/packages/62/1e/a94a8d635fa3ce4cfc7f506003548d0a2447ae76fd5ca53932970fe3053f/pyasn1-0.4.8-py2.py3-none-any.whl (77kB)
Apr 07 07:41:12 ip-x-x-x-x.ec2.internal user-data[1530]: Collecting futures<4.0.0,>=2.2.0; python_version == "2.7" (from s3transfer<0.4.0,>=0.3.0->awscli)
Apr 07 07:41:12 ip-x-x-x-x.ec2.internal user-data[1530]:   Downloading https://files.pythonhosted.org/packages/d8/a6/f46ae3f1da0cd4361c344888f59ec2f5785e69c872e175a748ef6071cdb5/futures-3.3.0-py2-none-any.whl
Apr 07 07:41:12 ip-x-x-x-x.ec2.internal user-data[1530]: Collecting urllib3<1.27,>=1.25.4 (from botocore==1.20.46->awscli)
Apr 07 07:41:12 ip-x-x-x-x.ec2.internal user-data[1530]:   Downloading https://files.pythonhosted.org/packages/09/c6/d3e3abe5b4f4f16cf0dfc9240ab7ce10c2baa0e268989a4e3ec19e90c84e/urllib3-1.26.4-py2.py3-none-any.whl (153kB)
Apr 07 07:41:12 ip-x-x-x-x.ec2.internal user-data[1530]: Collecting jmespath<1.0.0,>=0.7.1 (from botocore==1.20.46->awscli)
Apr 07 07:41:12 ip-x-x-x-x.ec2.internal user-data[1530]:   Downloading https://files.pythonhosted.org/packages/07/cb/5f001272b6faeb23c1c9e0acc04d48eaaf5c862c17709d20e3469c6e0139/jmespath-0.10.0-py2.py3-none-any.whl
Apr 07 07:41:12 ip-x-x-x-x.ec2.internal user-data[1530]: Collecting python-dateutil<3.0.0,>=2.1 (from botocore==1.20.46->awscli)
Apr 07 07:41:12 ip-x-x-x-x.ec2.internal user-data[1530]:   Downloading https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl (227kB)
Apr 07 07:41:12 ip-x-x-x-x.ec2.internal user-data[1530]: Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in /usr/lib/python2.7/site-packages (from python-dateutil<3.0.0,>=2.1->botocore==1.20.46->awscli)
Apr 07 07:41:12 ip-x-x-x-x.ec2.internal user-data[1530]: Installing collected packages: pyasn1, rsa, colorama, futures, urllib3, jmespath, python-dateutil, botocore, s3transfer, docutils, awscli
Apr 07 07:41:12 ip-x-x-x-x.ec2.internal user-data[1530]:   Found existing installation: urllib3 1.10.2
Apr 07 07:41:12 ip-x-x-x-x.ec2.internal user-data[1530]:     Uninstalling urllib3-1.10.2:
Apr 07 07:41:12 ip-x-x-x-x.ec2.internal user-data[1530]:       Successfully uninstalled urllib3-1.10.2
Apr 07 07:41:14 ip-x-x-x-x.ec2.internal user-data[1530]: Successfully installed awscli-1.19.46 botocore-1.20.46 colorama-0.4.3 docutils-0.15.2 futures-3.3.0 jmespath-0.10.0 pyasn1-0.4.8 python-dateutil-2.8.1 rsa-4.5 s3transfer-0.3.6 urllib3-1.26.4
Apr 07 07:41:14 ip-x-x-x-x.ec2.internal user-data[1530]: You are using pip version 8.1.2, however version 21.0.1 is available.
Apr 07 07:41:14 ip-x-x-x-x.ec2.internal user-data[1530]: You should consider upgrading via the 'pip install --upgrade pip' command.
`

**Comment by nateprewitt** [comment]
One commonality I'm seeing in the provided info is `pip` installations older than 9.0 (released 2016). This is the version that's considered the earliest point most modern Python packaging features were all available. Both the CLI and its dependencies release artifacts with the assumption end-users are using `pip>=9.0`.

For anyone still experiencing issues on Python 2.7, we'd recommend upgrading `pip` to 9.0 or later. If you're upgrading `pip` with a version of `pip` older than 9.0, you'll likely have issues with a standard `pip install --upgrade pip`. This is because that version of `pip` can't detect the latest _compatible_ version and grabs the latest release (which doesn't support Python 2).

In that case, we'd recommend upgrading to a supported version for Python 2.7. That would be any version between 9.0 and 20.3.4 (`pip install --upgrade pip>=9.0,<=20.3.4`). We would _highly_ discourage upgrading `setuptools` independently, because it's quite easy to break older versions of `pip` by upgrading dependencies underneath it.

**Comment by naman1-gupta** [comment]
I was facing a similar but not the exact same issue with the release of aws-cli v1.19.45 but it got automatically fixed in v1.19.46 and it has now come back in v1.19.48

```
Collecting awscli
  Downloading https://files.pythonhosted.org/packages/10/00/fc506c3bbeaec4ab4da4c33194582b85e0e0d6452a6f14aba6fff66c6b33/awscli-1.19.48.tar.gz (1.4MB)
    100% |████████████████████████████████| 1.4MB 771kB/s eta 0:00:011
Exception:
Traceback (most recent call last):
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pip/commands/install.py", line 299, in run
    requirement_set.prepare_files(finder)
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pip/req/req_set.py", line 647, in _prepare_file
    set(req_to_install.extras) - set(dist.extras)
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2810, in extras
    return [dep for dep in self._dep_map if dep]
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2624, in _dep_map
    dm.setdefault(extra,[]).extend(parse_requirements(reqs))
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2980, in parse_requirements
    "version spec")
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2956, in scan_list
    raise RequirementParseError(msg, line, "at", line[p:])
RequirementParseError: Expected ',' or end-of-list in rsa>=3.1.2,<=4.5.0; python_version=="2.7" at ; python_version=="2.7"
```

**Comment by kdaily** [comment]
Thanks @nateprewitt! Marking this as resolved.
