### ISSUE TITLE
S3 sync: s3 -> local redownloads unchanged files

### ISSUE THREAD

**Issue by laupow** [aws/aws-cli#648]
We store a pile of files in S3 and it's handy to have a local copy of our S3 buckets for development and backup. Upon first glance `aws s3 sync` looks like it'll work. 

I ran sync on our entire bucket and it completed successfully; it downloaded a whole bucket to local disk. The second time I ran the command it was redownloaded some files that haven't changed (on S3 or locally) alongside the new ones.

```
sh-3.2# aws s3 sync s3://serc serc
download: s3://serc/files/NAGTWorkshops/gsa03/activities/EET_Poster.pdf to serc/files/NAGTWorkshops/gsa03/activities/EET_Poster.pdf
download: s3://serc/files/NAGTWorkshops/rtop/genetics_40_minutes.v3.mp4 to serc/files/NAGTWorkshops/rtop/genetics_40_minutes.v3.mp4
download: s3://serc/files/NAGTWorkshops/rtop/introductory_meteorology.mov to serc/files/NAGTWorkshops/rtop/introductory_meteorology.mov
... 5000 more files ...
```

These files were just downloaded with the first `sync`. The local modified time & size match S3's values.

While I never rule out the possibility of user error I don't see an obvious cause. The first S3->Local sync completed normally, I run it again and it redownloads _some_ files every time that haven't changed. Not all, just some. And it's the same files  redownloaded every time.

My cli version is `aws-cli/1.2.13 Python/2.7.6 Darwin/10.8.0`
This may or may not be related to issue #599, but I won't personally make that call.

**Comment by JaredNJames** [comment]
Not sure why this has been marked closed.  Currently experiencing a similar issue:

https://github.com/aws/aws-cli/issues/1268#issuecomment-90659182

**Comment by reverie** [comment]
@jamesls I'm also not sure this is fixed. I can run an s3 sync twice in a row. Out of ~10k files, the same ~80 get re-downloaded every time. Nothing comes up for the 'comparator' grep, though.

**Comment by chops888** [comment]
I am having the same issues once "--exact-timestamps" is turned on. Randomly, multiple old files in the same bucket download to local machine. Next sync they're fine. Ran it with --debug | grep 'modified time' and noticed that the timestamps were all off by 1 second every time this anomaly occurs. The comparison is in [this file](https://github.com/aws/aws-cli/blob/develop/awscli/customizations/s3/syncstrategy/exacttimestamps.py) and I think ill just mod it to ignore diffs of < 2 seconds. That'll work for me, anyway. Hope this helps someone else.

**Comment by reverie** [comment]
Even with --size-only I get dupes. Some of them are files that have the same filename with different capitalizations, so that may be one issue.

**Comment by chops888** [comment]
Different capitalization == different file in linux, thus probably with awscli, even on windows. I would definitely expect that behavior on Linux.

**Comment by chops888** [comment]
@reverie - run the sync with debug on and try to find the lines where the program is comparing size and stamp and filename. Look for the reason it wants to sync a particular file.

**Comment by reverie** [comment]
Re: capitalization, I'm not surprised that it's treating them as different files. I'm surprised that it's re-syncing them every time. Anyway, that's only some of them. Looks from the log like "file does not exist at destination" is the given reason for syncing.

**Comment by chops888** [comment]
Looks like I've created a workaround for my issue by changing line 40 in exacttimestamps.py from
`return self.total_seconds(delta) == 0`
to
`return self.total_seconds(delta) > -1`

**Comment by chops888** [comment]
Actually, 
`return -1 < self.total_seconds(delta) < 1`
is probably safer.

**Comment by zaphod-42** [comment]
This continues to be an issue, with the latest aws cli installed I still have about 100 files out of roughly 200k that continue to download on every sync.

**Comment by chops888** [comment]
Did you edit exacttimestamps.py as indicated above? This should fix the issue until you update awscli again

**Comment by chops888** [comment]
On one of my servers this file is located at /usr/local/lib/python2.7/dist-packages/awscli/customizations/s3/syncstrategy/exacttimestamps.py

**Comment by zaphod-42** [comment]
I wan't using the --exact-timestamps flag, but I'll check it out

**Comment by zaphod-42** [comment]
That didn't fix it for me, I also tried with  "--dryrun --debug 2>&1 | grep comparator" and got no output

**Comment by chops888** [comment]
Do you get anything relevant without piping to grep? Also in sizeonly.py - you could mod the debug output to include src_file.size and dst_file.size to see exact what values the two sizes are on the files that are continually resyncing.

**Comment by zaphod-42** [comment]
Ok, I created a second local directory so I could target one of the directories, instead of running through 260k files every time, I have the same problem, so I grepped for a specific filename and got this (I added the astrix) :

MainThread - awscli.customizations.s3.syncstrategy.base - DEBUG - syncing: ***/***/wp-content/uploads/2017/03/DOC_image10-1-1-150x150.png -> /Volumes/Backup/tmp_backup/DOC_image10-1-1-150x150.png, file does not exist at destination
(dryrun) download: s3://***/***wp-content/uploads/2017/03/DOC_image10-1-1-150x150.png to tmp_backup/DOC_image10-1-1-150x150.png

I've run it 3 times, and get the same result every time (I run an actual sync in between the debugs)

**Comment by zaphod-42** [comment]
So evidently, the files are never being created locally, I did double check and that seems to be the case. That file is never added

**Comment by chops888** [comment]
huh. Well that explains why they try to download every time, but not why they're failing to write in the first place. Dont suppose the destination is windows and the total filename with folders length is too long? If windows, run procmon to see why its failing to write.

**Comment by zaphod-42** [comment]
Nope, destination is a mac, and that's not even the longest filename in the directory, I checked and there are longer filenames that sync successfully

**Comment by zaphod-42** [comment]
I've also checked S3 to make sure the file isn't corrupt or something, but I can view it without issue. The only thing I can see is that most of the other files have been updated at least once since this bucket was set to be revisioned, but I'm not sure why that would cause an issue

**Comment by chops888** [comment]
How about deleting and re-uploading the problem files in the bucket?

**Comment by zaphod-42** [comment]
wow, no luck with that either. Well, at least it's friday, maybe I'll  have a eureka moment over the weekend

**Comment by FrontSide** [comment]
Happening for me too. When I do a sync from the bucket to a local disc it re-downloads every single file each time. No laughs.

**Comment by jquast** [comment]
Saw this too, and it was because the files were from the future. In my case, 5 of 10,000 files kept re-downloading, and these 5 files were dated 2018, and its currently the year 2017.

**Comment by wpccolorblind** [comment]
Seeing the same.

**Comment by arieljlira** [comment]
Similar issue here when mirroring local folder to s3 bucket. Aws cli re-uploads a modified same file several times ( Ec2 instance,  CentOS Linux release 7.5.1804, aws-cli/1.16.89 )
In my case system clock was several seconds ahead of real clock so I activated chronyd (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html) and it fixed the system clock by -67.612530 seconds.
Now every aws-cli sync uploads files only the first time, as expected.

**Comment by yvele** [comment]
Same problem from S3 to S3 all the files already has been copied using sync, and when I re-run the same sync lots of files are copied again! `file does not exist at destination`

I'm using `aws-cli/1.16.150 Python/3.7.3 Darwin/16.7.0 botocore/1.12.140`

**Comment by cmcfarling** [comment]
Same issue when syncing local directory to S3 on Windows. Of about 8GB of data, it wants to re-copy about 1GB every time. Even though the files exist on the destination the dryrun debug command is reporting that the files don't exist. Here's just one example:

`2019-12-13 15:50:30,391 - MainThread - awscli.customizations.s3.syncstrategy.base - DEBUG - syncing: E:\ServerFolders\ADDRESS.DAT -> bucket1/Archive/ADDRESS.DAT, file does not exist at destination`

**Comment by joirramalho** [comment]
Seeing the same.
